version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mosaic-store
      - SPRING_DATASOURCE_USERNAME=mosaic
      - SPRING_DATASOURCE_PASSWORD=mosaic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_PRODUCT_FOLDER=${AWS_S3_PRODUCT_FOLDER}
      - AWS_S3_VARIANT_FOLDER=${AWS_S3_VARIANT_FOLDER}
    networks:
      - mosaic-network

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mosaic-store
      - POSTGRES_USER=mosaic
      - POSTGRES_PASSWORD=mosaic
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mosaic-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - mosaic-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mosaic.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mosaic-network

networks:
  mosaic-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: