aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    product-image-folder: ${AWS_S3_PRODUCT_FOLDER}
    product-variant-image-folder: ${AWS_S3_VARIANT_FOLDER}
spring:
  application:
    name: EXE-Mosaic-BE
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaic-store
    username: mosaic
    password: mosaic
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

api:
  prefix: /api/v1
