aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    product-image-folder: ${AWS_S3_PRODUCT_FOLDER}
    product-variant-image-folder: ${AWS_S3_VARIANT_FOLDER}
spring:
  application:
    name: EXE-Mosaic-BE
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaic-store
    username: mosaic
    password: mosaic
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    jdbc:
      dialect: postgresql
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 10000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: "optional:file:.env[.properties]"
app:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_BASE64_SECRET_KEY}
        token-validity-in-seconds: 900
        refresh-token:
          token-validity-in-seconds: 86400
          token-validity-in-seconds-for-remember-me: 2592000
  otp:
    expiry-minutes: 5
    max-attempts: 3

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

api:
  prefix: /api/v1
