spring:
  application:
    name: EXE-Mosaic-BE
  datasource:
    url: jdbc:postgresql://localhost:5432/mosaic-store
    username: mosaic
    password: mosaic
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics


api:
  prefix:/api/v1
